/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catatalumni;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.List;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import koneksi.Koneksi;

/**
 *
 * @author Administrator
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    int x;
    int y;
    boolean mousePress;
    
    public MainMenu() {
        initComponents();
        drag();
        load_table();
        count_alumni();
    }
    
    public void drag() {
        addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent me){
                mousePress = true;
                x = me.getX();
                y = me.getY();
            }
            public void mouseReleased(MouseEvent me){
                mousePress = false;
            }
        });
        
        addMouseMotionListener(new MouseMotionAdapter(){
            public void mouseDragged(MouseEvent me){
                if (mousePress = true){
                    int tX = MainMenu.this.getLocation().x + me.getX();
                    int tY = MainMenu.this.getLocation().y + me.getY();
                    
                    int X = tX - x;
                    int Y = tY - y;
                    
                    MainMenu.this.setLocation(X, Y);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDefault = new javax.swing.JPanel();
        panelUtama = new javax.swing.JPanel();
        panelWadah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        textTambah = new javax.swing.JLabel();
        buttonLihat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textLihat = new javax.swing.JLabel();
        buttonPengaturan = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        textPengaturan = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        textLogout = new javax.swing.JLabel();
        panelTambah = new javax.swing.JPanel();
        panelWadahTambah = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelWadahFieldTambah = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pickJurusan = new javax.swing.JComboBox<>();
        fieldTahun = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        fieldStatus = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        fieldNomorHP = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        pickUmur = new javax.swing.JSpinner();
        buttonTambahAlumni = new javax.swing.JPanel();
        textTambahAlumni = new javax.swing.JLabel();
        buttonBackTambah = new javax.swing.JPanel();
        textBackTambah = new javax.swing.JLabel();
        panelLihat = new javax.swing.JPanel();
        panelWadah1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_alumni = new javax.swing.JTable();
        buttonBackLihat = new javax.swing.JPanel();
        textBackLihat = new javax.swing.JLabel();
        fieldSearch = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        panelWadahTambah1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelWadahFieldTambah1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fieldEditNama = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        pickEditJurusan = new javax.swing.JComboBox<>();
        fieldEditTahun = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        fieldEditStatus = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        fieldEditNomorHP = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        pickEditUmur = new javax.swing.JSpinner();
        buttonEditAlumni = new javax.swing.JPanel();
        textTambahAlumni1 = new javax.swing.JLabel();
        buttonBackEdit = new javax.swing.JPanel();
        textBackEdit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelDefault.setBackground(new java.awt.Color(124, 148, 115));
        panelDefault.setLayout(new java.awt.CardLayout());

        panelUtama.setBackground(new java.awt.Color(124, 148, 115));

        panelWadah.setBackground(new java.awt.Color(232, 234, 230));
        panelWadah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 234, 230), 1, true));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(81, 96, 75));
        jLabel1.setText("Selamat Datang!");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(81, 96, 75));
        jLabel2.setText("Total Alumni yang Sudah Terdaftar :");

        total.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(81, 96, 75));
        total.setText("x");

        javax.swing.GroupLayout panelWadahLayout = new javax.swing.GroupLayout(panelWadah);
        panelWadah.setLayout(panelWadahLayout);
        panelWadahLayout.setHorizontalGroup(
            panelWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadahLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelWadahLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        panelWadahLayout.setVerticalGroup(
            panelWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWadahLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(total))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        buttonTambah.setBackground(new java.awt.Color(232, 234, 230));
        buttonTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonTambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonTambahMouseReleased(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user(1).png"))); // NOI18N
        buttonTambah.add(jLabel22);

        textTambah.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textTambah.setForeground(new java.awt.Color(81, 96, 75));
        textTambah.setText("Tambah Alumni");
        buttonTambah.add(textTambah);

        buttonLihat.setBackground(new java.awt.Color(232, 234, 230));
        buttonLihat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonLihat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLihat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLihatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonLihatMouseReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/files(1).png"))); // NOI18N
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        buttonLihat.add(jLabel3);

        textLihat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textLihat.setForeground(new java.awt.Color(81, 96, 75));
        textLihat.setText("Lihat Alumni");
        buttonLihat.add(textLihat);

        buttonPengaturan.setBackground(new java.awt.Color(232, 234, 230));
        buttonPengaturan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonPengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPengaturanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonPengaturanMouseReleased(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/setting-lines(1).png"))); // NOI18N
        buttonPengaturan.add(jLabel23);

        textPengaturan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textPengaturan.setForeground(new java.awt.Color(81, 96, 75));
        textPengaturan.setText("Pengaturan");
        buttonPengaturan.add(textPengaturan);

        buttonLogout.setBackground(new java.awt.Color(232, 234, 230));
        buttonLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonLogoutMouseReleased(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout(1).png"))); // NOI18N
        buttonLogout.add(jLabel24);

        textLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textLogout.setForeground(new java.awt.Color(81, 96, 75));
        textLogout.setText("Logout Aplikasi");
        buttonLogout.add(textLogout);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(buttonLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(buttonPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelWadah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(panelWadah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        panelDefault.add(panelUtama, "cardUtama");

        panelTambah.setBackground(new java.awt.Color(124, 148, 115));

        panelWadahTambah.setBackground(new java.awt.Color(207, 218, 200));
        panelWadahTambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 234, 230), 1, true));
        panelWadahTambah.setPreferredSize(new java.awt.Dimension(698, 165));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(81, 96, 75));
        jLabel4.setText("Tambah Alumni");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(81, 96, 75));
        jLabel5.setText("Tambah Alumni ke Database, Pastikan Data yang Diinput Benar");

        javax.swing.GroupLayout panelWadahTambahLayout = new javax.swing.GroupLayout(panelWadahTambah);
        panelWadahTambah.setLayout(panelWadahTambahLayout);
        panelWadahTambahLayout.setHorizontalGroup(
            panelWadahTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadahTambahLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelWadahTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        panelWadahTambahLayout.setVerticalGroup(
            panelWadahTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWadahTambahLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelWadahFieldTambah.setBackground(new java.awt.Color(207, 218, 200));
        panelWadahFieldTambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 234, 230), 1, true));
        panelWadahFieldTambah.setPreferredSize(new java.awt.Dimension(698, 165));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(81, 96, 75));
        jLabel6.setText("Nama");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(81, 96, 75));
        jLabel7.setText("Tahun Kelulusan");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(81, 96, 75));
        jLabel8.setText("Jurusan");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(81, 96, 75));
        jLabel9.setText("Status");

        fieldNama.setBackground(new java.awt.Color(207, 218, 200));
        fieldNama.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldNama.setForeground(new java.awt.Color(81, 96, 75));
        fieldNama.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator1.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 3));

        pickJurusan.setBackground(new java.awt.Color(207, 218, 200));
        pickJurusan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pickJurusan.setForeground(new java.awt.Color(81, 96, 75));
        pickJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RPL", "TKJ", "OTKP", "MP", "TKR" }));
        pickJurusan.setBorder(null);
        pickJurusan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pickJurusan.setFocusable(false);
        pickJurusan.setOpaque(false);

        fieldTahun.setBackground(new java.awt.Color(207, 218, 200));
        fieldTahun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldTahun.setForeground(new java.awt.Color(81, 96, 75));
        fieldTahun.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator2.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 3));

        fieldStatus.setBackground(new java.awt.Color(207, 218, 200));
        fieldStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldStatus.setForeground(new java.awt.Color(81, 96, 75));
        fieldStatus.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator3.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 3));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(81, 96, 75));
        jLabel10.setText("Nomor HP / WA");

        fieldNomorHP.setBackground(new java.awt.Color(207, 218, 200));
        fieldNomorHP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldNomorHP.setForeground(new java.awt.Color(81, 96, 75));
        fieldNomorHP.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator4.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 3));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(81, 96, 75));
        jLabel11.setText("Umur");

        pickUmur.setOpaque(false);

        buttonTambahAlumni.setBackground(new java.awt.Color(81, 96, 75));
        buttonTambahAlumni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonTambahAlumni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTambahAlumni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonTambahAlumniMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonTambahAlumniMouseReleased(evt);
            }
        });

        textTambahAlumni.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textTambahAlumni.setForeground(new java.awt.Color(232, 234, 230));
        textTambahAlumni.setText("Tambahkan ke Database");
        buttonTambahAlumni.add(textTambahAlumni);

        javax.swing.GroupLayout panelWadahFieldTambahLayout = new javax.swing.GroupLayout(panelWadahFieldTambah);
        panelWadahFieldTambah.setLayout(panelWadahFieldTambahLayout);
        panelWadahFieldTambahLayout.setHorizontalGroup(
            panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                        .addComponent(buttonTambahAlumni, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                        .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(108, 108, 108)
                                .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNomorHP, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(pickUmur)
                            .addComponent(pickJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldStatus))
                        .addGap(88, 88, 88))))
        );
        panelWadahFieldTambahLayout.setVerticalGroup(
            panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(pickUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                        .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fieldTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(pickJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                        .addGroup(panelWadahFieldTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fieldNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWadahFieldTambahLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTambahAlumni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonBackTambah.setBackground(new java.awt.Color(207, 218, 200));
        buttonBackTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonBackTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBackTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBackTambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonBackTambahMouseReleased(evt);
            }
        });

        textBackTambah.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textBackTambah.setForeground(new java.awt.Color(81, 96, 75));
        textBackTambah.setText("Kembali ke Halaman Utama");
        buttonBackTambah.add(textBackTambah);

        javax.swing.GroupLayout panelTambahLayout = new javax.swing.GroupLayout(panelTambah);
        panelTambah.setLayout(panelTambahLayout);
        panelTambahLayout.setHorizontalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWadahFieldTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelWadahTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBackTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelTambahLayout.setVerticalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(panelWadahTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelWadahFieldTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonBackTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelDefault.add(panelTambah, "cardTambah");

        panelLihat.setBackground(new java.awt.Color(124, 148, 115));

        panelWadah1.setBackground(new java.awt.Color(207, 218, 200));
        panelWadah1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 234, 230), 1, true));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(81, 96, 75));
        jLabel12.setText("Lihat Alumni");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(81, 96, 75));
        jLabel13.setText("Klik Kolom Tabel untuk Edit atau Hapus Data Alumni");

        javax.swing.GroupLayout panelWadah1Layout = new javax.swing.GroupLayout(panelWadah1);
        panelWadah1.setLayout(panelWadah1Layout);
        panelWadah1Layout.setHorizontalGroup(
            panelWadah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadah1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelWadah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        panelWadah1Layout.setVerticalGroup(
            panelWadah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWadah1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        table_alumni.setShowGrid(true);
        table_alumni.setDefaultEditor(Object.class, null);
        table_alumni.setAutoCreateRowSorter(true);

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(table_alumni.getModel());
        table_alumni.setRowSorter(sorter);
        table_alumni.setBackground(new java.awt.Color(207, 218, 200));
        table_alumni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        table_alumni.getTableHeader().setBackground(new Color(207, 218, 200));
        table_alumni.getTableHeader().setForeground(new Color(81, 96, 75));
        table_alumni.getTableHeader().setFont(new java.awt.Font("Arial", 1, 14));
        table_alumni.setForeground(new java.awt.Color(81, 96, 75));
        table_alumni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_alumni.setEditingColumn(0);
        table_alumni.setGridColor(new java.awt.Color(232, 234, 230));
        table_alumni.setOpaque(false);
        table_alumni.setRowHeight(20);
        table_alumni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_alumniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_alumni);

        buttonBackLihat.setBackground(new java.awt.Color(207, 218, 200));
        buttonBackLihat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonBackLihat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBackLihat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBackLihatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonBackLihatMouseReleased(evt);
            }
        });

        textBackLihat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textBackLihat.setForeground(new java.awt.Color(81, 96, 75));
        textBackLihat.setText("Kembali ke Halaman Utama");
        buttonBackLihat.add(textBackLihat);

        fieldSearch.setBackground(new java.awt.Color(207, 218, 200));
        fieldSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldSearch.setForeground(new java.awt.Color(81, 96, 75));
        fieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSearchKeyReleased(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(232, 234, 230));
        jLabel25.setText("Cari :");

        javax.swing.GroupLayout panelLihatLayout = new javax.swing.GroupLayout(panelLihat);
        panelLihat.setLayout(panelLihatLayout);
        panelLihatLayout.setHorizontalGroup(
            panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLihatLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonBackLihat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelWadah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGroup(panelLihatLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelLihatLayout.setVerticalGroup(
            panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLihatLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(panelWadah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBackLihat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelDefault.add(panelLihat, "cardLihat");

        panelEdit.setBackground(new java.awt.Color(124, 148, 115));

        panelWadahTambah1.setBackground(new java.awt.Color(207, 218, 200));
        panelWadahTambah1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 234, 230), 1, true));
        panelWadahTambah1.setPreferredSize(new java.awt.Dimension(698, 165));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(81, 96, 75));
        jLabel14.setText("Edit Alumni");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(81, 96, 75));
        jLabel15.setText("Edit Data Alumni");

        javax.swing.GroupLayout panelWadahTambah1Layout = new javax.swing.GroupLayout(panelWadahTambah1);
        panelWadahTambah1.setLayout(panelWadahTambah1Layout);
        panelWadahTambah1Layout.setHorizontalGroup(
            panelWadahTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadahTambah1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelWadahTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        panelWadahTambah1Layout.setVerticalGroup(
            panelWadahTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWadahTambah1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelWadahFieldTambah1.setBackground(new java.awt.Color(207, 218, 200));
        panelWadahFieldTambah1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 234, 230), 1, true));
        panelWadahFieldTambah1.setPreferredSize(new java.awt.Dimension(698, 165));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(81, 96, 75));
        jLabel16.setText("Nama");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(81, 96, 75));
        jLabel17.setText("Tahun Kelulusan");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(81, 96, 75));
        jLabel18.setText("Jurusan");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(81, 96, 75));
        jLabel19.setText("Status");

        fieldEditNama.setBackground(new java.awt.Color(207, 218, 200));
        fieldEditNama.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldEditNama.setForeground(new java.awt.Color(81, 96, 75));
        fieldEditNama.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator5.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 3));

        pickEditJurusan.setBackground(new java.awt.Color(207, 218, 200));
        pickEditJurusan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pickEditJurusan.setForeground(new java.awt.Color(81, 96, 75));
        pickEditJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RPL", "TKJ", "OTKP", "MP", "TKR" }));
        pickEditJurusan.setBorder(null);
        pickEditJurusan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pickEditJurusan.setFocusable(false);
        pickEditJurusan.setOpaque(false);

        fieldEditTahun.setBackground(new java.awt.Color(207, 218, 200));
        fieldEditTahun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldEditTahun.setForeground(new java.awt.Color(81, 96, 75));
        fieldEditTahun.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator6.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator6.setPreferredSize(new java.awt.Dimension(0, 3));

        fieldEditStatus.setBackground(new java.awt.Color(207, 218, 200));
        fieldEditStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldEditStatus.setForeground(new java.awt.Color(81, 96, 75));
        fieldEditStatus.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator7.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator7.setPreferredSize(new java.awt.Dimension(0, 3));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(81, 96, 75));
        jLabel20.setText("Nomor HP / WA");

        fieldEditNomorHP.setBackground(new java.awt.Color(207, 218, 200));
        fieldEditNomorHP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldEditNomorHP.setForeground(new java.awt.Color(81, 96, 75));
        fieldEditNomorHP.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(81, 96, 75));
        jSeparator8.setForeground(new java.awt.Color(81, 96, 75));
        jSeparator8.setPreferredSize(new java.awt.Dimension(0, 3));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(81, 96, 75));
        jLabel21.setText("Umur");

        pickEditUmur.setOpaque(false);

        buttonEditAlumni.setBackground(new java.awt.Color(81, 96, 75));
        buttonEditAlumni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonEditAlumni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEditAlumni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonEditAlumniMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonEditAlumniMouseReleased(evt);
            }
        });

        textTambahAlumni1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textTambahAlumni1.setForeground(new java.awt.Color(232, 234, 230));
        textTambahAlumni1.setText("Update ke Database");
        buttonEditAlumni.add(textTambahAlumni1);

        javax.swing.GroupLayout panelWadahFieldTambah1Layout = new javax.swing.GroupLayout(panelWadahFieldTambah1);
        panelWadahFieldTambah1.setLayout(panelWadahFieldTambah1Layout);
        panelWadahFieldTambah1Layout.setHorizontalGroup(
            panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                        .addComponent(buttonEditAlumni, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                        .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldEditTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(108, 108, 108)
                                .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldEditNomorHP, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(pickEditUmur)
                            .addComponent(pickEditJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldEditStatus))
                        .addGap(88, 88, 88))))
        );
        panelWadahFieldTambah1Layout.setVerticalGroup(
            panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(pickEditUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                        .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(fieldEditTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(pickEditJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                        .addGroup(panelWadahFieldTambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(fieldEditNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWadahFieldTambah1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldEditStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditAlumni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonBackEdit.setBackground(new java.awt.Color(207, 218, 200));
        buttonBackEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(232, 234, 230), new java.awt.Color(205, 208, 203), null));
        buttonBackEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBackEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBackEditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonBackEditMouseReleased(evt);
            }
        });

        textBackEdit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textBackEdit.setForeground(new java.awt.Color(81, 96, 75));
        textBackEdit.setText("Kembali ke Lihat Alumni");
        buttonBackEdit.add(textBackEdit);

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWadahFieldTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelWadahTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBackEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(panelWadahTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelWadahFieldTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonBackEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelDefault.add(panelEdit, "cardEdit");

        getContentPane().add(panelDefault, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogoutMouseReleased
        buttonLogout.setBackground(new Color(232, 234, 230));
        textLogout.setForeground(new Color(81,96,75));

        int jawab = JOptionPane.showOptionDialog(this,
            "Ingin Logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Sesi telah berakhir, silahkan login kembali");
            System.exit(0);
        }
    }//GEN-LAST:event_buttonLogoutMouseReleased

    private void buttonLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogoutMousePressed
        buttonLogout.setBackground(new Color(207, 218, 200));
        textLogout.setForeground(new Color(124, 148, 115));
    }//GEN-LAST:event_buttonLogoutMousePressed

    private void buttonPengaturanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPengaturanMouseReleased
        buttonPengaturan.setBackground(new Color(232, 234, 230));
        textPengaturan.setForeground(new Color(81,96,75));
    }//GEN-LAST:event_buttonPengaturanMouseReleased

    private void buttonPengaturanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPengaturanMousePressed
        buttonPengaturan.setBackground(new Color(207, 218, 200));
        textPengaturan.setForeground(new Color(124, 148, 115));
    }//GEN-LAST:event_buttonPengaturanMousePressed

    private void buttonLihatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLihatMouseReleased
        buttonLihat.setBackground(new Color(232, 234, 230));
        textLihat.setForeground(new Color(81,96,75));
        
        CardLayout card = (CardLayout)panelDefault.getLayout();
        card.show(panelDefault, "cardLihat");
    }//GEN-LAST:event_buttonLihatMouseReleased

    private void buttonLihatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLihatMousePressed
        buttonLihat.setBackground(new Color(207, 218, 200));
        textLihat.setForeground(new Color(124, 148, 115));
    }//GEN-LAST:event_buttonLihatMousePressed

    private void buttonTambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahMouseReleased
        buttonTambah.setBackground(new Color(232, 234, 230));
        textTambah.setForeground(new Color(81,96,75));
        
        CardLayout card = (CardLayout)panelDefault.getLayout();
        card.show(panelDefault, "cardTambah");
        
    }//GEN-LAST:event_buttonTambahMouseReleased

    private void buttonTambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahMousePressed
        buttonTambah.setBackground(new Color(207, 218, 200));
        textTambah.setForeground(new Color(124, 148, 115));
    }//GEN-LAST:event_buttonTambahMousePressed

    private void buttonTambahAlumniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahAlumniMousePressed
        buttonTambahAlumni.setBackground(new Color(124, 148, 115));
        textTambahAlumni.setForeground(new Color(81,96,75));
    }//GEN-LAST:event_buttonTambahAlumniMousePressed

    private void buttonTambahAlumniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahAlumniMouseReleased
        buttonTambahAlumni.setBackground(new Color(81,96,75));
        textTambahAlumni.setForeground(new Color(232,234,230));
        
        try{
            String sql = "INSERT INTO `alumni` (`nama_lengkap`, `umur`, `tahun_kelulusan`, `jurusan`, `nomor_hp`, `status`) VALUES ('"+fieldNama.getText()+"', '"+pickUmur.getValue()+"', '"+fieldTahun.getText()+"', '"+pickJurusan.getSelectedItem()+"', '"+fieldNomorHP.getText()+"', '"+fieldStatus.getText()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            update_table();
            
            JOptionPane.showMessageDialog(null, "Data telah terkirim", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonTambahAlumniMouseReleased

    private void buttonBackTambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackTambahMousePressed
        buttonBackTambah.setBackground(new Color(207, 218, 200));
        textBackTambah.setForeground(new Color(124, 148, 115));
         try {
            String sql = "SELECT COUNT(*) AS jumlahalumni FROM alumni;";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet s = pst.executeQuery();
            
            s.next();
            total.setText(String.valueOf(s.getInt(1) + " orang"));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonBackTambahMousePressed

    private void buttonBackTambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackTambahMouseReleased
        buttonBackTambah.setBackground(new Color(207,218,200));
        textBackTambah.setForeground(new Color(81,96,75));
        
        CardLayout card = (CardLayout)panelDefault.getLayout();
        card.show(panelDefault, "cardUtama");
    }//GEN-LAST:event_buttonBackTambahMouseReleased

    private void buttonBackLihatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackLihatMouseReleased
        buttonBackLihat.setBackground(new Color(207,218,200));
        textBackLihat.setForeground(new Color(81,96,75));
        
        CardLayout card = (CardLayout)panelDefault.getLayout();
        card.show(panelDefault, "cardUtama");
         try {
            String sql = "SELECT COUNT(*) AS jumlahalumni FROM alumni;";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet s = pst.executeQuery();
            
            s.next();
            total.setText(String.valueOf(s.getInt(1) + " orang"));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonBackLihatMouseReleased

    private void buttonBackLihatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackLihatMousePressed
        buttonBackLihat.setBackground(new Color(207, 218, 200));
        textBackLihat.setForeground(new Color(124, 148, 115));
    }//GEN-LAST:event_buttonBackLihatMousePressed

    private void table_alumniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_alumniMouseClicked
        int baris = table_alumni.rowAtPoint(evt.getPoint());
        
        Object[] options = {"Edit Data", "Hapus Data"};
        
        int n = JOptionPane.showOptionDialog(this, "Pilih Aksi", "Mau diapain?",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        
        if (n == 1) {
            System.out.println("you choose " + n);
            try {
                String sql ="DELETE FROM alumni WHERE id_alumni='"+table_alumni.getValueAt(baris, 0)+"'";
                java.sql.Connection conn=(Connection)Koneksi.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Berhasil di hapus");
                update_table();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else if (n == 0){
            System.out.println("you choose" + n);
            
            CardLayout card = (CardLayout)panelDefault.getLayout();
            card.show(panelDefault, "cardEdit");
            
            String id = table_alumni.getValueAt(baris, 0).toString();
            idAlumni = id;
            String nama = table_alumni.getValueAt(baris, 1).toString();
            fieldEditNama.setText(nama);
            String umur = table_alumni.getValueAt(baris, 2).toString();
            pickEditUmur.setValue(Integer.valueOf(umur));
            String tahun = table_alumni.getValueAt(baris, 3).toString();
            fieldEditTahun.setText(tahun);
            String jurusan = table_alumni.getValueAt(baris, 4).toString();
            pickEditJurusan.setSelectedItem(jurusan);
            String nomorhp = table_alumni.getValueAt(baris, 5).toString();
            fieldEditNomorHP.setText(nomorhp);
            String status = table_alumni.getValueAt(baris, 6).toString();
            fieldEditStatus.setText(status);
        } else {
            
        }
    }//GEN-LAST:event_table_alumniMouseClicked

    private void buttonEditAlumniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditAlumniMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditAlumniMousePressed

    private void buttonEditAlumniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditAlumniMouseReleased
        try{
            String sql = "UPDATE alumni SET nama_lengkap = '"+fieldEditNama.getText()+
            "', umur = '"+pickEditUmur.getValue()+
            "', tahun_kelulusan = '"+fieldEditTahun.getText()+
            "', jurusan = '"+pickEditJurusan.getSelectedItem()+
            "', nomor_hp = '"+fieldEditNomorHP.getText()+
            "', status = '"+fieldEditStatus.getText()+
            "' WHERE id_alumni = '"+idAlumni+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            update_table();

            JOptionPane.showMessageDialog(null, "Data telah berubah", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonEditAlumniMouseReleased

    private void buttonBackEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackEditMousePressed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Lengkap");
        model.addColumn("Umur");
        model.addColumn("Tahun Kelulusan");
        model.addColumn("Jurusan");
        model.addColumn("Nomor HP");
        model.addColumn("Status");
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "SELECT * FROM alumni";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            int i = 1;
            while(res.next()){
                model.addRow(new Object[]{Integer.parseInt(res.getString(1)),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            table_alumni.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonBackEditMousePressed

    private void buttonBackEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackEditMouseReleased
        CardLayout card = (CardLayout)panelDefault.getLayout();
        card.show(panelDefault, "cardLihat");
    }//GEN-LAST:event_buttonBackEditMouseReleased

    private void fieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchKeyReleased
        DefaultTableModel model = (DefaultTableModel) table_alumni.getModel();
        
        String cari = fieldSearch.getText();
        
        TableRowSorter tr = new TableRowSorter(model);
        table_alumni.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(cari));
    }//GEN-LAST:event_fieldSearchKeyReleased
    
    private String idAlumni;
    
    public void setidAlumni(String IDAlumni){
        idAlumni = IDAlumni;
    }
    
    public String getidAlumni() {
        return idAlumni;
    }
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Lengkap");
        model.addColumn("Umur");
        model.addColumn("Tahun Kelulusan");
        model.addColumn("Jurusan");
        model.addColumn("Nomor HP");
        model.addColumn("Status");
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "SELECT * FROM alumni";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            int i = 1;
            while(res.next()){
                model.addRow(new Object[]{Integer.parseInt(res.getString(1)),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            table_alumni.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
    private void update_table() {     
        DefaultTableModel model = (DefaultTableModel) table_alumni.getModel();
        model.setRowCount(0);
        
        load_table();
    }
    
    private void count_alumni() {
        try {
            String sql = "SELECT COUNT(*) AS jumlahalumni FROM alumni;";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet s = pst.executeQuery();
            
            s.next();
            total.setText(String.valueOf(s.getInt(1) + " orang"));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonBackEdit;
    private javax.swing.JPanel buttonBackLihat;
    private javax.swing.JPanel buttonBackTambah;
    private javax.swing.JPanel buttonEditAlumni;
    private javax.swing.JPanel buttonLihat;
    private javax.swing.JPanel buttonLogout;
    private javax.swing.JPanel buttonPengaturan;
    private javax.swing.JPanel buttonTambah;
    private javax.swing.JPanel buttonTambahAlumni;
    private javax.swing.JTextField fieldEditNama;
    private javax.swing.JTextField fieldEditNomorHP;
    private javax.swing.JTextField fieldEditStatus;
    private javax.swing.JTextField fieldEditTahun;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNomorHP;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JTextField fieldStatus;
    private javax.swing.JTextField fieldTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel panelDefault;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelLihat;
    private javax.swing.JPanel panelTambah;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel panelWadah;
    private javax.swing.JPanel panelWadah1;
    private javax.swing.JPanel panelWadahFieldTambah;
    private javax.swing.JPanel panelWadahFieldTambah1;
    private javax.swing.JPanel panelWadahTambah;
    private javax.swing.JPanel panelWadahTambah1;
    private javax.swing.JComboBox<String> pickEditJurusan;
    private javax.swing.JSpinner pickEditUmur;
    private javax.swing.JComboBox<String> pickJurusan;
    private javax.swing.JSpinner pickUmur;
    private javax.swing.JTable table_alumni;
    private javax.swing.JLabel textBackEdit;
    private javax.swing.JLabel textBackLihat;
    private javax.swing.JLabel textBackTambah;
    private javax.swing.JLabel textLihat;
    private javax.swing.JLabel textLogout;
    private javax.swing.JLabel textPengaturan;
    private javax.swing.JLabel textTambah;
    private javax.swing.JLabel textTambahAlumni;
    private javax.swing.JLabel textTambahAlumni1;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
